name: learn
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ^3.0.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  rxdart: ^0.27.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.10
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/